routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { 
    return view('index');
});

/*
Route::get('/signup', function () {
    return view('signup');
});

Route::get('/signin', function () {
    return view('signin');
});
*/ 

Route::get('/admin', 'AdminController@index');
Route::post('/admin/search', 'AdminController@searchByName');
Route::get('/cat/{cat_id}', 'AdminController@searchKategori');

Route::get('/showask/{ask_id}', 'ShowAskController@index');
Route::post('/showask/c/', 'ShowAskController@setclose');
Route::post('/showask/h', 'ShowAskController@helpfull');
Route::post('/showask/sv', 'ShowAskController@setjawaban');

Route::resource('kategori','KategoriController'); 

Auth::routes(); 

Route::get('/home', 'AdminController@index')->name('home');

Route::resource('/profile', 'ProfileController')->only([
    'index', 'update', 'edit'
]);

Route::resource('tanya','TanyaController'); 

Route::post('/upload-image', 'TanyaController@upload');

Route::get('/print-pdf', 'ReportController@show');

Route::get('/saveitem/{tanya_id}', 'SaveitemsController@saveitem');

Route::get('/saveitem', 'SaveitemsController@index');

Route::get('/myactivity', 'AktifitasController@index')->name('aktifitas.index');

app/Tanya.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tanya extends Model
{  
    protected $table = 'tanya';
	protected $fillable = ["user_id", "tgljam", "judul", "pertanyaan", "isclosed"];
    protected $guarded = ['updated_at, created_at'];
	 
	public function user()
  	{
    	return $this->hasMany('App\User');
  	}

	  public function jawab()
  	{
    	return $this->hasMany('App\Jawab');
  	}
}

app/Http/Controllers/TanyaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tanya;
use App\Kategori;
use App\Kategori_pertanyaan;
use App\Aktifitas;
use Illuminate\Support\Facades\Auth;
use DB;
use RealRashid\SweetAlert\Facades\Alert;

class TanyaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index(){
        $tanya = Tanya::where('user_id', Auth::id())->orderBy('tgljam', 'desc')->get();
        $kategori = DB::table('kategori_pertanyaan')
            ->join('kategori', 'kategori_id', '=', 'kategori.id')
            ->join('tanya', 'tanya_id', '=', 'tanya.id')
            ->select('kategori_pertanyaan.*', 'kategori.*', 'tanya.*')
            ->get();

        return view('tanya.index', compact('tanya', 'kategori'));
    }

    public function create()
    {
        $kategori = Kategori::all();
        return view('tanya.create', compact('kategori'));
    }

    public function upload(Request $request)
    {
        $fileName=time().$request->file('file')->getClientOriginalName();
        $path=$request->file('file')->storeAs('uploads', $fileName, 'public');
        return response()->json(['location'=>"/storage/$path"]); ;
    }


    public function store(Request $request){
        $this->validate($request,[
            'judul' => 'required',
            'pertanyaan' => 'required',
        ]);
        // dd($request);
        $tanya = new Tanya;
        $tanya->tgljam = date('YmdHis');
        $tanya->judul = $request->judul;
        $tanya->pertanyaan = $request->pertanyaan;
        $tanya->isClosed = 0;
        $tanya->user_id = Auth::id();
        
        $tanya->save();

        foreach ($request->all() as $key => $value) {
            if($key != "_token" && $key != "judul" && $key != "pertanyaan"){
                // dd($value);
                $kategoriPertanyaan = new Kategori_pertanyaan;
 
                $kategoriPertanyaan->tanya_id = $tanya->id;
                $kategoriPertanyaan->kategori_id = $value;
                
                $kategoriPertanyaan->save();
            }
        }

        $aktifitas = new Aktifitas;
        $aktifitas->tgljam = date('YmdHis');
        $aktifitas->nama_aktifitas = "Post Pertanyaan";
        $aktifitas->deskripsi = $request->judul;
        $aktifitas->user_id = Auth::id();

        $aktifitas->save();

        return redirect('tanya');
    }

    public function show($id)
    {
        $tanya = Tanya::find($id);
        $kategori = DB::table('kategori_pertanyaan')
            ->join('kategori', 'kategori_id', '=', 'kategori.id')
            ->join('tanya', 'tanya_id', '=', 'tanya.id')
            ->select('kategori_pertanyaan.*', 'kategori.*', 'tanya.*')
            ->get();
        return view('tanya.show', compact('tanya', 'kategori'));
    }


    public function edit($id){
        $tanya = Tanya::find($id);
        $kategori = Kategori::all();
        $kategoriPertanyaan = Kategori_Pertanyaan::where('tanya_id', $id)->get();
        return view('tanya.edit', compact('tanya', 'kategori', 'kategoriPertanyaan'));
    }

    public function update($id, Request $request){
        // dd($request);
        $this->validate($request,[
            'judul' => 'required',
            'pertanyaan' => 'required',
        ]);

        $tanya = Tanya::find($id);

        $tanya->judul = $request->judul;
        $tanya->pertanyaan = $request->pertanyaan;
        
        $tanya->save();

        $currentKategoriPertanyaan = Kategori_Pertanyaan::where('tanya_id', $id)->get();
        // dd($currentKategoriPertanyaan);
        foreach ($currentKategoriPertanyaan as $value) {
            $deletedRows = Kategori_pertanyaan::where('id', $value->id)->delete();
        }

        foreach ($request->all() as $key => $value) {
            // dd($value);
            if($key != "_token" && $key != "_method" && $key != "judul" && $key != "pertanyaan"){
                $kategoriPertanyaan = new Kategori_pertanyaan;
 
                $kategoriPertanyaan->tanya_id = $tanya->id;
                $kategoriPertanyaan->kategori_id = $value;
                
                $kategoriPertanyaan->save();
            }
        }

        $aktifitas = new Aktifitas;
        $aktifitas->tgljam = date('YmdHis');
        $aktifitas->nama_aktifitas = "Edit Pertanyaan";
        $aktifitas->deskripsi = $request->judul;
        $aktifitas->user_id = Auth::id();

        $aktifitas->save();
        // menampilkan pesan berhasil
        Alert::success('Yeaaayy', 'Data Berhasil diperbaharui');

        return redirect('/tanya');
    }

    public function destroy($id)
    {
        $kategoriPertanyaan = Kategori_pertanyaan::where('tanya_id', $id)->get();
        foreach ($kategoriPertanyaan as $item) {
            $item->delete();
        }
        $tanya = Tanya::find($id);
        $aktifitas = new Aktifitas;
        $aktifitas->tgljam = date('YmdHis');
        $aktifitas->nama_aktifitas = "Delete Pertanyaan";
        $aktifitas->deskripsi = $tanya->judul;
        $aktifitas->user_id = Auth::id();

        $aktifitas->save();
        $tanya->delete();


        // menampilkan pesan berhasil
        Alert::success('Yeaaayy', 'Data Pertanyaan berhasil dihapus');

        return redirect('/tanya');
    }
}

resources/views/tanya/create.blade.php
@extends('adminlte.master')

@section('content') 
	<div align="center">		
		<h5>Posting Pertanyaan</h5>
		<hr />
	</div>
	
	<form action="{{ route('tanya.index') }}" method="post">
	@csrf
	<div class="card-body">
		<div class="form-group">
			<label for="judul">Judul</label>
			<input type="text" class="form-control" id="judul" name="judul" placeholder="" value="{{ old('judul', '') }}">
			@error('judul')
				<div class="alert alert-danger">{{ $message }}</div>
			@enderror
		</div>

		<div class="form-group my-3">
			<label for="pertanyaan">Pertanyaan</label>
			<textarea class="form-control" id="pertanyaan" name="pertanyaan" placeholder="" >{{ old('pertanyaan', '') }}</textarea>
			@error('pertanyaan')
				<div class="alert alert-danger">{{ $message }}</div>
			@enderror
		</div>
		
		<div class="form-group mb-3">
			<label>Kategori</label>
			<br><br>
			@forelse ($kategori as $key => $value)
				<div class="form-check form-check-inline my-1 mx-n2">
					<input class="btn-check" name="{{$key+1}}" type="checkbox" value="{{$value->id}}" id="kategori{{$key}}">
					<label class="btn btn-outline-success btn-sm" for="kategori{{$key}}">
						{{$value->namakategori}}
					</label>
				</div>
			@empty
				<p>Kategori tidak tersedia</p>
			@endforelse
		</div>
		
		<div class="card-footer">
			<button type="submit" class="btn btn-primary">Post</button>
			<button type="button" class="btn btn-primary" onclick="document.location.href='{{ route('tanya.index') }}'">Cancel</button>
		</div>
	</form>
@endsection

@push('scripts')
	{{-- <script src="{{asset('tinymce/tinymce.min.js')}}" referrerpolicy="origin"></script> --}}
	<script src="https://cdn.tiny.cloud/1/t5n49s9tn5kfe9n6dl38k7x49n05u3ys2abkt3uo20s517hp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
	<script>
		tinymce.init({
		  selector: '#pertanyaan',
		  height: 500,
            setup: function (editor) {
                editor.on('init change', function () {
                    editor.save();
                });
            },
            plugins: [
                "advlist autolink lists link image charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste imagetools"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            content_css: [
                '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                '//www.tinymce.com/css/codepen.min.css'
            ],
			convert_urls: false,
			image_title: true,
			automatic_uploads: true,
			images_upload_url: '/upload-image',
			file_picker_types: 'image',
			file_picker_callback: function(cb, value, meta) {
                var input = document.createElement('input');
                input.setAttribute('type', 'file');
                input.setAttribute('accept', 'image/*');
                input.onchange = function() {
                    var file = this.files[0];

                    var reader = new FileReader();
                    reader.readAsDataURL(file);
                    reader.onload = function () {
                        var id = 'blobid' + (new Date()).getTime();
                        var blobCache =  tinymce.activeEditor.editorUpload.blobCache;
                        var base64 = reader.result.split(',')[1];
                        var blobInfo = blobCache.create(id, file, base64);
                        blobCache.add(blobInfo);
                        cb(blobInfo.blobUri(), { title: file.name });
                    };
                };
                input.click();
            }
		});
	  </script>
@endpush

resources/views/tanya/edit.blade.php
@extends('adminlte.master')

@section('content') 
	<div align="center">		
		<h5>Edit Pertanyaan</h5>
		<hr />
	</div>
	
	<form action="/tanya/{{$tanya->id}}" method="post">
	@csrf
    @method('put')
	<div class="card-body">
		<div class="form-group">
			<label for="judul">Judul</label>
			<input type="text" class="form-control" id="judul" name="judul" placeholder="" value="{{ old('judul', $tanya->judul) }}">
			@error('judul')
				<div class="alert alert-danger">{{ $message }}</div>
			@enderror
		</div>

		<div class="form-group my-3">
			<label for="pertanyaan">Pertanyaan</label>
			<textarea class="form-control" id="pertanyaan" name="pertanyaan" placeholder="" >{{ old('pertanyaan', $tanya->pertanyaan) }}</textarea>
			@error('pertanyaan')
				<div class="alert alert-danger">{{ $message }}</div>
			@enderror
		</div>
		
		<div class="form-group mb-3">
			<label>Kategori</label>
			<br><br>
			@forelse ($kategori as $key => $value)
                <div class="form-check form-check-inline my-1 mx-n2">
                    <input class="btn-check" name="{{$key+1}}" type="checkbox" value="{{$value->id}}" id="kategori{{$key}}" 
                        @foreach ($kategoriPertanyaan as $item)
                            @if ($item->kategori_id == $value->id)
                                checked
                            @endif
                        @endforeach
                        >
                    <label class="btn btn-outline-success btn-sm" for="kategori{{$key}}">
                        {{$value->namakategori}}
                    </label>
                </div>
            @empty
            <p>Kategori tidak tersedia</p>
			@endforelse
		</div>
		
		<div class="card-footer">
			<button type="submit" class="btn btn-primary">Post</button>
			<button type="button" class="btn btn-primary" onclick="document.location.href='{{ route('tanya.index') }}'">Cancel</button>
		</div>
	</form>
@endsection

@push('scripts')
<script src="https://cdn.tiny.cloud/1/t5n49s9tn5kfe9n6dl38k7x49n05u3ys2abkt3uo20s517hp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script><script>
		tinymce.init({
		  selector: '#pertanyaan',
		  height: 500,
            setup: function (editor) {
                editor.on('init change', function () {
                    editor.save();
                });
            },
            plugins: [
                "advlist autolink lists link image charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste imagetools"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            content_css: [
                '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                '//www.tinymce.com/css/codepen.min.css'
            ],
            convert_urls: false,
			image_title: true,
			automatic_uploads: true,
			images_upload_url: '/upload-image',
			file_picker_types: 'image',
			file_picker_callback: function(cb, value, meta) {
                var input = document.createElement('input');
                input.setAttribute('type', 'file');
                input.setAttribute('accept', 'image/*');
                input.onchange = function() {
                    var file = this.files[0];

                    var reader = new FileReader();
                    reader.readAsDataURL(file);
                    reader.onload = function () {
                        var id = 'blobid' + (new Date()).getTime();
                        var blobCache =  tinymce.activeEditor.editorUpload.blobCache;
                        var base64 = reader.result.split(',')[1];
                        var blobInfo = blobCache.create(id, file, base64);
                        blobCache.add(blobInfo);
                        cb(blobInfo.blobUri(), { title: file.name });
                    };
                };
                input.click();
            }
		});
	  </script>
@endpush

resources/views/tanya/index.blade.php
@extends('adminlte.master')

@section('content') 
	
	<div class="card-body">
		<div class="w-100 align-items-center justify-content-between">
			<center>
				<h1>My Q & A</h1>
			</center>
			<a href="{{ route('tanya.create') }}" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Buat Pertanyaan</a>
		</div>
		<hr/>
			@forelse ($tanya as $key=>$value)
			
			<div class="row g-4 mb-3">
				<div class="col-sm-12 col-md-6 col-xl-12">
					
					<div class="d-flex w-100 align-items-center justify-content-between">
						<div>
							<h4 class="d-inline">{{$value->judul}}</h4>	<br>			
							<small>
								You opened this issue on <?=$formatDate = date('M d, Y', strtotime($value->tgljam))?> | 
								@if($value->isclosed == 0)				
									<i class="fa fa-times"></i>
								@else 
									<i class="fa fa-check"></i>
								@endif
								 {{count(App\Tanya::find($value->id)->jawab)}} Answers
							</small>
							<div>
								<small><b>Category :</b> 
									@forelse ($kategori as $item)
										@if ($item->tanya_id == $value->id)
											<div class="btn btn-secondary btn-sm rounded-pill my-2" style="cursor:none; font-size:10px">
												{{$item->namakategori}}
											</div>
										@endif
									@empty
										No kategori
									@endforelse
								</small>
							</div>
							<div class="d-flex my-2">
								<a href="/tanya/{{$value->id}}" class="btn btn-primary btn-sm"><i class="fa fa-eye"></i> Detail</a>
								<a class="btn btn-info btn-sm mx-2" href="/tanya/{{$value->id}}/edit"><i class="bi bi-pencil-square"></i>Edit</a>
    
								<form action="{{ route('tanya.destroy', ['tanya' => $value->id] ) }}" method="POST">
									@csrf
									@method('DELETE')
									
									<button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash"> </i> Delete</button>
								</form>
							</div>
						</div>	
		
						@if($value->isclosed == 0)				
							<button type="button" class="btn btn-sm btn-success rounded-pill m-2" style="cursor:none; font-size:10px"><i class="fa fa-times"></i> Opened</button>
						@else 
							<button type="button" class="btn btn-sm btn-danger rounded-pill" style="cursor:none; font-size:10px"><i class="fa fa-check-circle"></i> Closed</button>
						@endif
					</div>								
					<hr />
																		
					{{-- <div class="alert alert-info alert-dismissible fade show" role="alert">
						<div>
							<img class="rounded-circle me-lg-2" src="{{ asset('/adminlte/img/user.jpg') }}" alt="" style="width: 40px; height: 40px;">
							<small>{{Auth::user()->name}} question on {{$formatDate}} </small>
							<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
						</div>
						<hr />
						<div class="alert alert-light" role="alert">
							{!! $value->pertanyaan !!}								
						</div>																	
					</div> --}}
				</div>	
			</div>
			@empty
				<p>No Data</p>
			@endforelse              
	</div>
	
@endsection

@push('scripts')
	
@endpush

resources/views/tanya/show.blade.php
@extends('adminlte.master')

@section('content') 
	
<div class="row g-4">
	<div class="col-sm-12 col-md-6 col-xl-12">
		
		<div class="d-flex w-100 align-items-center justify-content-between">
			<div>
				
				<h4>{{$tanya->judul}}</h4>				
				<small>{{Auth::user()->name}} opened this issue on <?=$formatDate = date('M d, Y', strtotime($tanya->tgljam))?> | <i class="fa fa-times"></i> 2 Answers</small>
				<div>
					<small><b>Category :</b> 
						@forelse ($kategori as $item)
							@if ($item->tanya_id == $tanya->id)
								<div class="btn btn-secondary btn-sm rounded-pill my-2" style="cursor:none; font-size:10px">
									{{$item->namakategori}}
								</div>
							@endif
						@empty
							No kategori
						@endforelse
					</small>
				</div>
			</div>	
			
			@if($tanya->isclosed == 0)				
				<button type="button" class="btn btn-sm btn-success rounded-pill m-2" style="cursor:none; font-size:10px"><i class="fa fa-times"></i> Opened</button>
			@else 
				<button type="button" class="btn btn-sm btn-danger rounded-pill" style="cursor:none; font-size:10px"><i class="fa fa-check-circle"></i> Closed</button>
			@endif
		</div>								
		<hr />
															
		<div class="alert alert-info alert-dismissible fade show" role="alert">
			<div>
				<img class="rounded-circle me-lg-2" src="{{ asset('/adminlte/img/user.jpg') }}" alt="" style="width: 40px; height: 40px;">
				<small>{{Auth::user()->name}} question on {{$formatDate}} </small>
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
			<hr />
			<div class="alert alert-light" role="alert">
				{!! $tanya->pertanyaan !!}								
			</div>	
			<a class="btn btn-primary" href="/showask/{{$tanya->id}}" role="button"><i class="fas fa-location-arrow"></i> Go To Post</a>
			<a class="btn btn-outline-success" href="/saveitem/{{$tanya->id}}" role="button"><i class="fas fa-bookmark"></i>  Save</a>																
		</div>
		
		<hr />
		<h5>{{count(App\Tanya::find($tanya->id)->jawab)}} Answers</h5>
		
		@forelse (App\Tanya::find($tanya->id)->jawab as $key => $value)
			<div class="alert alert-secondary">
				<div>
					@if (!App\User::find($value->user_id)->profile->avatar == null)
						<img src="{{ asset('images/' . App\User::find($value->user_id)->profile->avatar) }}" alt="thumbnail_profile" class="rounded-circle" width="40px" height="40px">
					@else
						<img src="{{ asset('images/default-profile.png') }}" alt="thumbnail_profile" class="rounded-circle" width="40px" height="40px">            
					@endif
					<small class="mx-2">{{App\User::find($value->user_id)->name}} comment on {{$formatDate = date('M d, Y', strtotime($value->tgljam))}}</small>
					
				</div>
				<hr />
				@if ($value->issolutions != 0)
					<div class="btn btn-success rounded-pill mb-3"><i class="fa fa-check"></i> Solution</div>
				@endif
				<div class="alert alert-light" role="alert">
					{!!$value->jawaban!!}
				</div>	
				
			</div>
		@empty
			<p>No Comment Available</p>
		@endforelse
		
	</div>
									
</div>
	
@endsection

@push('scripts')
	
@endpush