routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () { 
    return view('index');
});

/*
Route::get('/signup', function () {
    return view('signup');
});

Route::get('/signin', function () {
    return view('signin');
});
*/ 

Route::get('/admin', 'AdminController@index');
Route::post('/admin/search', 'AdminController@searchByName');
Route::get('/cat/{cat_id}', 'AdminController@searchKategori');

Route::get('/showask/{ask_id}', 'ShowAskController@index');
Route::post('/showask/c/', 'ShowAskController@setclose');
Route::post('/showask/h', 'ShowAskController@helpfull');
Route::post('/showask/sv', 'ShowAskController@setjawaban');

Route::resource('kategori','KategoriController'); 

Auth::routes(); 

Route::get('/home', 'AdminController@index')->name('home');

Route::resource('/profile', 'ProfileController')->only([
    'index', 'update', 'edit'
]);

Route::resource('tanya','TanyaController'); 

Route::post('/upload-image', 'TanyaController@upload');

Route::get('/print-pdf', 'ReportController@show');

Route::get('/saveitem/{tanya_id}', 'SaveitemsController@saveitem');

Route::get('/saveitem', 'SaveitemsController@index');

Route::get('/myactivity', 'AktifitasController@index')->name('aktifitas.index');

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
	public $timestamps = false;
    protected $table = "kategori"; 
    protected $fillable = ["namakategori", "tglbuat"];

    public function kategori_pertanyaan(){
        return $this->hasMany('App\Kategori_pertanyaan');
    }
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades\Auth;
use App\Kategori;
use App\Kategori_pertanyaan;
use App\Aktifitas;

class KategoriController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Kategori::all();
        return view('kategori.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'namakategori' => 'required',
        ]);

        $kategori = new Kategori;

        $kategori->namakategori = $request->namakategori;
        $kategori->tglbuat = date('YmdHis');
        $kategori->save();

        $aktifitas = new Aktifitas;
        $aktifitas->tgljam = date('YmdHis');
        $aktifitas->nama_aktifitas = "Create Kategori";
        $aktifitas->deskripsi = $request->namakategori;
        $aktifitas->user_id = Auth::id();

        $aktifitas->save();

        // menampilkan pesan berhasil
        Alert::success('Yeaaayy', 'Data kategori berhasil ditambahkan');

        // Kategori::create([
    	// 	'namakategori' => $request->namakategori,
    	// 	'tglbuat' => date('YmdHis'),
		// 	'isdel' => '0',
		// 	'user_id' => $request->user_id
    	// ]);

 
    	return redirect('/kategori');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kategori = Kategori::find($id);
        return view('kategori.show', compact('kategori'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = Kategori::find($id);
        return view('kategori.edit', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'namakategori' => 'required',
        ]);

        //$kategori = Kategori::find($id);
	
		$kategori = Kategori::where('id',$id)->update([
    		'namakategori' => $request->namakategori,
    		'tglbuat' => date('YmdHis')
    	]);
		
		//$kategori->namakategori = $request->namakategori;
        //$kategori->tglbuat = date('YmdHis');
        // $kategori->isdel = 0;
        // $kategori->user_id = $request->user_id;
       // $kategori->save();
 

        $aktifitas = new Aktifitas;
        $aktifitas->tgljam = date('YmdHis');
        $aktifitas->nama_aktifitas = "Edit Kategori";
        $aktifitas->deskripsi = $request->namakategori;
        $aktifitas->user_id = Auth::id();

        $aktifitas->save();

		// menampilkan pesan berhasil
        Alert::success('Yeaaayy', 'Data kategori berhasil diperbaharui');

        return redirect('/kategori');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kategoriPertanyaan = Kategori_pertanyaan::where('kategori_id', $id)->get();
        foreach ($kategoriPertanyaan as $item) {
            $item->delete();
        }
        $kategori = Kategori::find($id);
        $aktifitas = new Aktifitas;
        $aktifitas->tgljam = date('YmdHis');
        $aktifitas->nama_aktifitas = "Delete Kategori";
        $aktifitas->deskripsi = $kategori->namakategori;
        $aktifitas->user_id = Auth::id();

        $aktifitas->save();
        $kategori->delete();


        // menampilkan pesan berhasil
        Alert::success('Yeaaayy', 'Data kategori berhasil dihapus');

        return redirect('/kategori');
    }
}

resources/views/kategori/create.blade.php
@extends('adminlte.master')

@section('content') 
	<div align="center">		
		<h5>Tambah Data</h5>
		<hr />
	</div>
	
	<form action="{{ route('kategori.index') }}" method="post">
	@csrf
	<div class="card-body">
		<div class="form-group">
		<input type="hidden" name="user_id" value="{{Auth::id()}}">
		<label for="exampleInputEmail1">Nama Kategori</label>
		<input type="text" class="form-control" id="namakategori" name="namakategori" placeholder="" value="{{ old('namakategori', '') }}">
		@error('namakategori')
			<div class="alert alert-danger">{{ $message }}</div>
		@enderror
		</div>
		
		
		</div>
		
		<div class="card-footer">
			<button type="submit" class="btn btn-primary">Save</button>
			<button type="button" class="btn btn-primary" onclick="document.location.href='{{ route('kategori.index') }}'">Cancel</button>
		</div>
	</form>
@endsection

@push('scripts')
	
@endpush

resources/views/kategori/edit.blade.php
@extends('adminlte.master')

@section('content') 
	
	<div class="card-body">		
		<div>
			<h2>Edit Data</h2>
			<form action="{{ route('kategori.update', ['kategori' => $kategori->id] ) }}" method="POST">
				@csrf
				@method('PUT')
				<div class="form-group">
					<label for="title">Nama Kategori</label>
					<input type="hidden" name="user_id" value="{{Auth::id()}}">
					<input type="text" class="form-control" name="namakategori" value="{{$kategori->namakategori}}" id="namakategori" placeholder="Masukkan Nama Kategori">
					@error('namakategori')
						<div class="alert alert-danger">
							{{ $message }}
						</div>
					@enderror
				</div>
				
				<hr />
				<button type="submit" class="btn btn-primary">Edit</button>
				<button type="button" class="btn btn-info" onclick="document.location.href='{{ route('kategori.index') }}'">Cancel</button>
			</form>
		</div>
	</div>
	
@endsection

@push('scripts')
	
@endpush

resources/views/kategori/index.blade.php
@extends('adminlte.master')

@section('content') 
	
	<div class="card-body">
		<div class="d-flex w-100 align-items-center justify-content-between">
			<a href="{{ route('kategori.create') }}" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Tambah</a>
			<h5>List Data Kategori</h5>
		</div>
		<hr/>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th style="width: 10px">#</th>
					<th>Nama Kategori</th>					
					<th style="width: 40px">Action</th>
				</tr>
			</thead>
			<tbody>
                @forelse ($data as $key=>$value)
                    <tr>
                        <td>{{$key + 1}}</th>
                        <td>{{$value->namakategori}}</td>                       
                        <td style="display:flex;">                          
							<button title="Show" type="button" style="margin:2px" class="btn btn-info" 
							onclick="document.location.href='{{ route('kategori.show', ['kategori' => $value->id] ) }}'"><i class="fa fa-search"></i></button>
							<button title="Edit" type="button" style="margin:2px" class="btn btn-primary" 
							onclick="document.location.href='{{ route('kategori.edit', ['kategori' => $value->id] ) }}'"><i class="fas fa-pencil-alt"></i></button>
							
                            <form action="{{ route('kategori.destroy', ['kategori' => $value->id] ) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                
								<button type="submit" title="Delete" style="margin:2px" class="btn btn-danger"><i class="fa fa-times"></i></button>
                            </form>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td  colspan="3"><div align="center">No data</div></td>
                    </tr>  
                @endforelse              
            </tbody>
		</table>
	</div>
	
@endsection

@push('scripts')
	
@endpush

resources/views/kategori/show.blade.php
@extends('adminlte.master')

@section('content') 
	
	<div class="card-body">		
		<div class="d-flex w-100 align-items-center justify-content-between">
			<button type="button" class="btn btn-primary" onclick="document.location.href='{{ route('kategori.index') }}'"><i class="fa fa-arrow-circle-left"></i> Back</button>
			<h5>View Data</h5>
		</div>
		<hr/>
		
		<h5>Nama Kategori : {{$kategori->namakategori}}</h5>
	</div>
	
@endsection

@push('scripts')
	
@endpush